version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: compose_zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: 
      context: kafka/
    container_name: compose_kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # add additional kafka params
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spark:
    build:
      context: spark/
    container_name: compose_spark
    ports:
      - "8080:8080"
      - "7077:7077"
    command: start-master.sh
 # zeppelin:
 #   build: zeppelin/.
  web:
    build: 
      context: webapp/
    container_name: compose_app
    ports: 
     - "5000:5000"
    volumes:
     - ./webapp:/code

