version: '2'
services:
  postgres:
    image: kiasaki/alpine-postgres
    container_name: compose_postgres
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow
    post:
      - "5432:5432"
  airflow:
      build: .
      user: airflow
      restart: always
      container_name: compose_airflow
      depends_on:
          - postgres
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
      volumes:
          - ./dags:/usr/local/airflow/dags
          - ~/.aws:/usr/local/airflow/.aws
      ports:
          - "8080:8080"
      command: entrypoint.sh webserver
      #command: /bin/bash